// Code generated by protoc-gen-go.
// source: read_proc.proto
// DO NOT EDIT!

/*
Package read_proc is a generated protocol buffer package.

It is generated from these files:
	read_proc.proto

It has these top-level messages:
	Request
	Response
	Header
	BarragePerSecond
	Body
*/
package read_proc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Header *Header `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Body   *Body   `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response struct {
	Header *Header `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Body   *Body   `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type Header struct {
	RoomId  uint32 `protobuf:"varint,1,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	RetMsg  string `protobuf:"bytes,3,opt,name=ret_msg,json=retMsg" json:"ret_msg,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Header) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *Header) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *Header) GetRetMsg() string {
	if m != nil {
		return m.RetMsg
	}
	return ""
}

type BarragePerSecond struct {
	Content []string `protobuf:"bytes,1,rep,name=content" json:"content,omitempty"`
}

func (m *BarragePerSecond) Reset()                    { *m = BarragePerSecond{} }
func (m *BarragePerSecond) String() string            { return proto.CompactTextString(m) }
func (*BarragePerSecond) ProtoMessage()               {}
func (*BarragePerSecond) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BarragePerSecond) GetContent() []string {
	if m != nil {
		return m.Content
	}
	return nil
}

type Body struct {
	Barrage []*BarragePerSecond `protobuf:"bytes,1,rep,name=barrage" json:"barrage,omitempty"`
}

func (m *Body) Reset()                    { *m = Body{} }
func (m *Body) String() string            { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()               {}
func (*Body) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Body) GetBarrage() []*BarragePerSecond {
	if m != nil {
		return m.Barrage
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "read_proc.Request")
	proto.RegisterType((*Response)(nil), "read_proc.Response")
	proto.RegisterType((*Header)(nil), "read_proc.Header")
	proto.RegisterType((*BarragePerSecond)(nil), "read_proc.BarragePerSecond")
	proto.RegisterType((*Body)(nil), "read_proc.Body")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ReadProc service

type ReadProcClient interface {
	// 定义SayHello方法
	SyncBarrage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type readProcClient struct {
	cc *grpc.ClientConn
}

func NewReadProcClient(cc *grpc.ClientConn) ReadProcClient {
	return &readProcClient{cc}
}

func (c *readProcClient) SyncBarrage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/read_proc.ReadProc/SyncBarrage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ReadProc service

type ReadProcServer interface {
	// 定义SayHello方法
	SyncBarrage(context.Context, *Request) (*Response, error)
}

func RegisterReadProcServer(s *grpc.Server, srv ReadProcServer) {
	s.RegisterService(&_ReadProc_serviceDesc, srv)
}

func _ReadProc_SyncBarrage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadProcServer).SyncBarrage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/read_proc.ReadProc/SyncBarrage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadProcServer).SyncBarrage(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReadProc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "read_proc.ReadProc",
	HandlerType: (*ReadProcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncBarrage",
			Handler:    _ReadProc_SyncBarrage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "read_proc.proto",
}

func init() { proto.RegisterFile("read_proc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x91, 0xb1, 0x4f, 0x83, 0x50,
	0x10, 0x87, 0xc5, 0x56, 0x68, 0x8f, 0x98, 0xea, 0x73, 0x10, 0x75, 0x69, 0x70, 0xc1, 0xc4, 0x74,
	0xc0, 0x98, 0xb8, 0xb8, 0xa0, 0x83, 0x0e, 0x26, 0xcd, 0x6b, 0x1c, 0xec, 0x42, 0xe0, 0xbd, 0x0b,
	0x3a, 0x94, 0xc3, 0xe3, 0x39, 0xf0, 0xdf, 0x1b, 0x1e, 0xd4, 0xa2, 0xb3, 0xe3, 0xdd, 0x7d, 0xbf,
	0x2f, 0x97, 0x3b, 0x98, 0x31, 0x66, 0x3a, 0xad, 0x98, 0xd4, 0xa2, 0x62, 0x32, 0x24, 0xa6, 0x3f,
	0x8d, 0xf0, 0x0d, 0x3c, 0x89, 0x9f, 0x5f, 0x58, 0x1b, 0x71, 0x05, 0xee, 0x3b, 0x66, 0x1a, 0x39,
	0x70, 0xe6, 0x4e, 0xe4, 0xc7, 0xc7, 0x8b, 0x5d, 0xee, 0xc9, 0x0e, 0x64, 0x0f, 0x88, 0x4b, 0x18,
	0xe7, 0xa4, 0x9b, 0x60, 0xdf, 0x82, 0xb3, 0x01, 0x98, 0x90, 0x6e, 0xa4, 0x1d, 0x86, 0x6b, 0x98,
	0x48, 0xac, 0x2b, 0x2a, 0x6b, 0xfc, 0x77, 0xf7, 0x2b, 0xb8, 0x5d, 0x4c, 0x9c, 0x82, 0xc7, 0x44,
	0x9b, 0xf4, 0x43, 0x5b, 0xf5, 0xa1, 0x74, 0xdb, 0xf2, 0x59, 0x8b, 0x33, 0x98, 0x30, 0x9a, 0x54,
	0x91, 0x46, 0xeb, 0x3a, 0x90, 0x1e, 0xa3, 0x79, 0x20, 0x8d, 0x36, 0x83, 0x26, 0xdd, 0xd4, 0x45,
	0x30, 0x9a, 0x3b, 0xd1, 0x54, 0xba, 0x8c, 0xe6, 0xa5, 0x2e, 0xc2, 0x6b, 0x38, 0x4a, 0x32, 0xe6,
	0xac, 0xc0, 0x25, 0xf2, 0x0a, 0x15, 0x95, 0x5a, 0x04, 0xe0, 0x29, 0x2a, 0x0d, 0x96, 0x26, 0x70,
	0xe6, 0xa3, 0x68, 0x2a, 0xb7, 0x65, 0x78, 0x0f, 0xe3, 0x76, 0x25, 0x71, 0x0b, 0x5e, 0xde, 0xa5,
	0x2c, 0xe1, 0xc7, 0x17, 0xc3, 0xa5, 0xff, 0xf8, 0xe4, 0x96, 0x8d, 0x1f, 0xdb, 0xfb, 0x64, 0x7a,
	0xc9, 0xa4, 0xc4, 0x1d, 0xf8, 0xab, 0xa6, 0x54, 0x3d, 0x2c, 0xc4, 0x40, 0xd0, 0xbf, 0xe7, 0xfc,
	0xe4, 0x57, 0xaf, 0xbb, 0x6b, 0xb8, 0x97, 0xf8, 0xeb, 0xdd, 0x37, 0x73, 0xd7, 0xfe, 0xf7, 0xe6,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x19, 0x8d, 0x6e, 0xf2, 0x01, 0x00, 0x00,
}
